-- Bug #2 Layer 2 — NULL logo_url for 165 stores Brandfetch has no real data for.
--
-- Audit method: curl'd each unique Brandfetch logo URL across all 572 active
-- stores using ?c=NEXT_PUBLIC_BRANDFETCH_CLIENT_ID, Chrome UA, couponawy Referer.
-- Sorted responses by exact byte size — Brandfetch's placeholders are byte-
-- identical across all domains they don't have data for:
--
--   426-byte response = empty fallback (no data at all)  → 97 domains
--   1742-byte response = generic 'B' brandmark placeholder → 68 domains
--                                                  TOTAL → 165 orphans
--
-- Strategy: NULL the orphan URL so the <StoreLogo> component falls through to
-- its existing initials-fallback (brand-red Arabic letters on cream-dark ring).
-- Visually consistent with the design system, no external dependency, and
-- significantly better than the alternative of rendering Brandfetch's 'B' icon.
--
-- Admins can paste a real logo URL via /admin/stores at any time. A periodic
-- re-audit cron could promote stores back to a real logo when Brandfetch adds
-- coverage — out of scope for this migration.
--
-- Reversible: re-running the audit would re-populate from the original URLs.
-- The Brandfetch URLs being NULL'd are still derivable from website_url.

UPDATE stores
SET logo_url = NULL, updated_at = NOW()
WHERE logo_url IN (
  'https://cdn.brandfetch.io/2b.com/w/256/h/256',
  'https://cdn.brandfetch.io/6thstreet.com/w/256/h/256',
  'https://cdn.brandfetch.io/aani-dani.com/w/256/h/256',
  'https://cdn.brandfetch.io/abdulsamad-alqurashi.com/w/256/h/256',
  'https://cdn.brandfetch.io/ajmal3tr.com/w/256/h/256',
  'https://cdn.brandfetch.io/ajmalperfume.com/w/256/h/256',
  'https://cdn.brandfetch.io/albrwaz.net/w/256/h/256',
  'https://cdn.brandfetch.io/aldo.com/w/256/h/256',
  'https://cdn.brandfetch.io/alezzoud.com/w/256/h/256',
  'https://cdn.brandfetch.io/alfaten.com/w/256/h/256',
  'https://cdn.brandfetch.io/alhabibmafresh.com/w/256/h/256',
  'https://cdn.brandfetch.io/almanea.sa/w/256/h/256',
  'https://cdn.brandfetch.io/almondhair.net/w/256/h/256',
  'https://cdn.brandfetch.io/alomar.com/w/256/h/256',
  'https://cdn.brandfetch.io/alrivan.com/w/256/h/256',
  'https://cdn.brandfetch.io/alriyfalnajdiu.com/w/256/h/256',
  'https://cdn.brandfetch.io/alshamalii.com/w/256/h/256',
  'https://cdn.brandfetch.io/alsinan.com/w/256/h/256',
  'https://cdn.brandfetch.io/altamimigroup.com/w/256/h/256',
  'https://cdn.brandfetch.io/ananclothes.com/w/256/h/256',
  'https://cdn.brandfetch.io/arganiabeauty.com/w/256/h/256',
  'https://cdn.brandfetch.io/aroom-wr.com/w/256/h/256',
  'https://cdn.brandfetch.io/asgharalistore.com/w/256/h/256',
  'https://cdn.brandfetch.io/asmaaboutique.com/w/256/h/256',
  'https://cdn.brandfetch.io/aster.sa/w/256/h/256',
  'https://cdn.brandfetch.io/ateeq-sa.com/w/256/h/256',
  'https://cdn.brandfetch.io/aya.app/w/256/h/256',
  'https://cdn.brandfetch.io/babyshopstores.com/w/256/h/256',
  'https://cdn.brandfetch.io/bandq.sa/w/256/h/256',
  'https://cdn.brandfetch.io/barllina.com/w/256/h/256',
  'https://cdn.brandfetch.io/bashrakare.com/w/256/h/256',
  'https://cdn.brandfetch.io/baytalsagheer.com/w/256/h/256',
  'https://cdn.brandfetch.io/beauti.sa/w/256/h/256',
  'https://cdn.brandfetch.io/beautymil.com/w/256/h/256',
  'https://cdn.brandfetch.io/berain.com/w/256/h/256',
  'https://cdn.brandfetch.io/bnat-ali.com/w/256/h/256',
  'https://cdn.brandfetch.io/bodyplus.com/w/256/h/256',
  'https://cdn.brandfetch.io/bohperfume.com/w/256/h/256',
  'https://cdn.brandfetch.io/boutiqaat.com/w/256/h/256',
  'https://cdn.brandfetch.io/brandsforless.com/w/256/h/256',
  'https://cdn.brandfetch.io/briv.sa/w/256/h/256',
  'https://cdn.brandfetch.io/calaisperfume.com/w/256/h/256',
  'https://cdn.brandfetch.io/cardinal.com.sa/w/256/h/256',
  'https://cdn.brandfetch.io/careem-food.com/w/256/h/256',
  'https://cdn.brandfetch.io/cb2.sa/w/256/h/256',
  'https://cdn.brandfetch.io/celebrityp.com/w/256/h/256',
  'https://cdn.brandfetch.io/centrepoint.com/w/256/h/256',
  'https://cdn.brandfetch.io/chicpoint.com/w/256/h/256',
  'https://cdn.brandfetch.io/crateandbarrel.me/w/256/h/256',
  'https://cdn.brandfetch.io/cvalley.sa/w/256/h/256',
  'https://cdn.brandfetch.io/daanah.com/w/256/h/256',
  'https://cdn.brandfetch.io/daralamirat.com/w/256/h/256',
  'https://cdn.brandfetch.io/darlina.sa/w/256/h/256',
  'https://cdn.brandfetch.io/dashstoresa.com/w/256/h/256',
  'https://cdn.brandfetch.io/debajsa.com/w/256/h/256',
  'https://cdn.brandfetch.io/debenhams.sa/w/256/h/256',
  'https://cdn.brandfetch.io/dermazone.sa/w/256/h/256',
  'https://cdn.brandfetch.io/detailsabaya.com/w/256/h/256',
  'https://cdn.brandfetch.io/doos.sa/w/256/h/256',
  'https://cdn.brandfetch.io/dragonmart.ae/w/256/h/256',
  'https://cdn.brandfetch.io/dropcake.sa/w/256/h/256',
  'https://cdn.brandfetch.io/drslounge.sa/w/256/h/256',
  'https://cdn.brandfetch.io/dukanqs.com/w/256/h/256',
  'https://cdn.brandfetch.io/dyson.sa/w/256/h/256',
  'https://cdn.brandfetch.io/ekar.app/w/256/h/256',
  'https://cdn.brandfetch.io/elabelz.com/w/256/h/256',
  'https://cdn.brandfetch.io/elegantie.market/w/256/h/256',
  'https://cdn.brandfetch.io/eleinwatches.com/w/256/h/256',
  'https://cdn.brandfetch.io/elfaleh.sa/w/256/h/256',
  'https://cdn.brandfetch.io/eoutlet.com/w/256/h/256',
  'https://cdn.brandfetch.io/evaegypt.com/w/256/h/256',
  'https://cdn.brandfetch.io/ezhalha.com.sa/w/256/h/256',
  'https://cdn.brandfetch.io/fabianksa.com/w/256/h/256',
  'https://cdn.brandfetch.io/fashion-sa.com/w/256/h/256',
  'https://cdn.brandfetch.io/feelunique.com/w/256/h/256',
  'https://cdn.brandfetch.io/fitnesstime.com/w/256/h/256',
  'https://cdn.brandfetch.io/flottlife.com/w/256/h/256',
  'https://cdn.brandfetch.io/gathern.com/w/256/h/256',
  'https://cdn.brandfetch.io/gildapearl.me/w/256/h/256',
  'https://cdn.brandfetch.io/goldenscent.com/w/256/h/256',
  'https://cdn.brandfetch.io/hana.com/w/256/h/256',
  'https://cdn.brandfetch.io/homeboxstores.com/w/256/h/256',
  'https://cdn.brandfetch.io/homesrus.com/w/256/h/256',
  'https://cdn.brandfetch.io/hometimeksa.com/w/256/h/256',
  'https://cdn.brandfetch.io/hoorabaya.com/w/256/h/256',
  'https://cdn.brandfetch.io/hsate.com/w/256/h/256',
  'https://cdn.brandfetch.io/ibrand.com/w/256/h/256',
  'https://cdn.brandfetch.io/ivalwater.com/w/256/h/256',
  'https://cdn.brandfetch.io/jamalon.com/w/256/h/256',
  'https://cdn.brandfetch.io/jeeny.com/w/256/h/256',
  'https://cdn.brandfetch.io/jofaboil.com/w/256/h/256',
  'https://cdn.brandfetch.io/joigifts.com/w/256/h/256',
  'https://cdn.brandfetch.io/jollychic.com/w/256/h/256',
  'https://cdn.brandfetch.io/kiehls.ae/w/256/h/256',
  'https://cdn.brandfetch.io/ksabeautycorner.com/w/256/h/256',
  'https://cdn.brandfetch.io/kunooz.com/w/256/h/256',
  'https://cdn.brandfetch.io/lafayettehoney.com/w/256/h/256',
  'https://cdn.brandfetch.io/lamier.com/w/256/h/256',
  'https://cdn.brandfetch.io/lebs.com/w/256/h/256',
  'https://cdn.brandfetch.io/lefties.com/w/256/h/256',
  'https://cdn.brandfetch.io/level.shoes/w/256/h/256',
  'https://cdn.brandfetch.io/like4card.com/w/256/h/256',
  'https://cdn.brandfetch.io/linzi.me/w/256/h/256',
  'https://cdn.brandfetch.io/loktstore.com/w/256/h/256',
  'https://cdn.brandfetch.io/lululemon.me/w/256/h/256',
  'https://cdn.brandfetch.io/madmoon.sa/w/256/h/256',
  'https://cdn.brandfetch.io/mafarshalayeri.com/w/256/h/256',
  'https://cdn.brandfetch.io/manukadose.com/w/256/h/256',
  'https://cdn.brandfetch.io/marksandspencerme.com/w/256/h/256',
  'https://cdn.brandfetch.io/mayalward.sa/w/256/h/256',
  'https://cdn.brandfetch.io/maysamco.com/w/256/h/256',
  'https://cdn.brandfetch.io/melsyasa.com/w/256/h/256',
  'https://cdn.brandfetch.io/miss-designs.com/w/256/h/256',
  'https://cdn.brandfetch.io/moyaapp.com/w/256/h/256',
  'https://cdn.brandfetch.io/mrmandob.com/w/256/h/256',
  'https://cdn.brandfetch.io/myhealthyway.com/w/256/h/256',
  'https://cdn.brandfetch.io/nafhat2018.com/w/256/h/256',
  'https://cdn.brandfetch.io/namshi.com/w/256/h/256',
  'https://cdn.brandfetch.io/natchostore.com/w/256/h/256',
  'https://cdn.brandfetch.io/naturaltouchshop.com/w/256/h/256',
  'https://cdn.brandfetch.io/navajewellery.sa/w/256/h/256',
  'https://cdn.brandfetch.io/niceface.sa/w/256/h/256',
  'https://cdn.brandfetch.io/niceone.com/w/256/h/256',
  'https://cdn.brandfetch.io/olinaksa.com/w/256/h/256',
  'https://cdn.brandfetch.io/oudelite.com/w/256/h/256',
  'https://cdn.brandfetch.io/panhomestores.com/w/256/h/256',
  'https://cdn.brandfetch.io/perfumeelegance.com/w/256/h/256',
  'https://cdn.brandfetch.io/petunia.sa/w/256/h/256',
  'https://cdn.brandfetch.io/qa-cosmetics.com/w/256/h/256',
  'https://cdn.brandfetch.io/qasralawaani.com/w/256/h/256',
  'https://cdn.brandfetch.io/qimmati.com/w/256/h/256',
  'https://cdn.brandfetch.io/raha.com/w/256/h/256',
  'https://cdn.brandfetch.io/rainycloudsog.com/w/256/h/256',
  'https://cdn.brandfetch.io/raseel.sa/w/256/h/256',
  'https://cdn.brandfetch.io/rehlat.com/w/256/h/256',
  'https://cdn.brandfetch.io/ribalpower.com/w/256/h/256',
  'https://cdn.brandfetch.io/riseshop.sa/w/256/h/256',
  'https://cdn.brandfetch.io/riva-fashion.com/w/256/h/256',
  'https://cdn.brandfetch.io/rosemaryparis.com/w/256/h/256',
  'https://cdn.brandfetch.io/ryouf.com/w/256/h/256',
  'https://cdn.brandfetch.io/saco.sa/w/256/h/256',
  'https://cdn.brandfetch.io/sallathayat.sa/w/256/h/256',
  'https://cdn.brandfetch.io/saramart.com/w/256/h/256',
  'https://cdn.brandfetch.io/selvium.com/w/256/h/256',
  'https://cdn.brandfetch.io/shawarmahouse.com/w/256/h/256',
  'https://cdn.brandfetch.io/shaykha90.com/w/256/h/256',
  'https://cdn.brandfetch.io/shgardi.app/w/256/h/256',
  'https://cdn.brandfetch.io/siklo.com/w/256/h/256',
  'https://cdn.brandfetch.io/sivvi.com/w/256/h/256',
  'https://cdn.brandfetch.io/soum.sa/w/256/h/256',
  'https://cdn.brandfetch.io/splash.ae/w/256/h/256',
  'https://cdn.brandfetch.io/sssports.com/w/256/h/256',
  'https://cdn.brandfetch.io/styli.com/w/256/h/256',
  'https://cdn.brandfetch.io/sugar-coated.com/w/256/h/256',
  'https://cdn.brandfetch.io/swisscorner.com/w/256/h/256',
  'https://cdn.brandfetch.io/takhayer.com/w/256/h/256',
  'https://cdn.brandfetch.io/tamanna.com/w/256/h/256',
  'https://cdn.brandfetch.io/tamkeenstores.com/w/256/h/256',
  'https://cdn.brandfetch.io/tern.sa/w/256/h/256',
  'https://cdn.brandfetch.io/thatconceptstore.com/w/256/h/256',
  'https://cdn.brandfetch.io/theidealhair-sa.com/w/256/h/256',
  'https://cdn.brandfetch.io/theoutnet.com/w/256/h/256',
  'https://cdn.brandfetch.io/toyo.sa/w/256/h/256',
  'https://cdn.brandfetch.io/warazan.com/w/256/h/256',
  'https://cdn.brandfetch.io/zareef.sa/w/256/h/256'
);
